F72744 cocohelper issues
AILAB-bh/cocohelper pull request #26
Opened 2024-10-02 14:59 UTC by paudaniele-bh

In this PR is been fixed some bug and added few capability, in particular:

1. Defined new requirements to support python >= 3.10 and updated environment.yml, pyproject.toml and readme accordingly with new version
3. [BUG] Modified stats.cat_nms_rations and stats.cat_ids_rations
4. [TEST] Modified test_stats to use pytest
5. [BUG] Typo in merge.py fixed
7. [BUG] merge._merge_categories: 'supercategory' key used as mandatory
8. [BUG] helper.COCOHelper.__init__: added DataFrame cols whether licenses is empty; it raised error during drop_duplicate_licenses function
10. [WARNING] helper.copy: solved warning bug due to COCODataFrame bad initialization of all the dataframes
11. [BUG] proportional._get_ids: fixed bug with k-splits, for k>2 (sometimes n_samples was incorrect).
12. [TEST] test_splitter: unit tests with pytest lib
13. [WARNING] dataframe.to_dict: solved pandas warning for future implementation of to_dict
14. [REFACTORING] Solved circular dependencies between COCOHelper and COCOValidator: added property to COCOHelper for creating a new validator to validate coco dataset during __init__ and copy
15. [CAPABILITY] helper.__init__: improved validation with a function that run the checks and raise an exception in case 1 or more checks are failed, it returns a log and a dict with all the data; helper.copy
16. [TEST] added unit tests for utils.segmentation; fixed minor bugs to make the unit tests pass.
17. [TEST] Converted unit tests for utils.segmentation to pytest format
18. [CAPABILITY] utils.segmentation: modified compression mechanism in polygon_to_mask function
19. [CAPABILITY/REFACTORING] created classes and polymorphism to handle the encoding/decoding of masks in different modalities (from/to RLE, cRLE, Polygon)
21. [DOC] Documentation and readme updated

2024-10-10 08:48 UTC, valvgab-bh requested changes
Good job Daniele :) Well done!

Could you please answer to the remaining questions?

2024-10-10 08:48 UTC, valvgab-bh commented on src/cocohelper/stats.py
>          return _df.to_dict()
I see you use `__get_category_ratios` instead of `__get_category_ratios`. I have two questions:
1) what is the difference?
2) Is the old `__get_category_ratios` still used in the code? or we should remove / deprecate it?

2024-10-10 08:48 UTC, valvgab-bh commented on tests/unit/test_cocohelper/test_dataset_adapter.py
> +def clean_saved_coco():
is this ever actually used?

2024-10-10 08:48 UTC, valvgab-bh commented on src/cocohelper/utils/segmentation.py
> +    return 'cRLE'
Here I would do a few modifications:
1) `isinstance `is usually faster than `type` and also considers inheritance. So it should be preferred
2) handle other input types with an exception
3) it is usually better to remove multiple returns in a function. Use `mode = ...` and then return `mode`

 For example, a better code could be:

```
if isinstance(segmentation, list):
    mode = 'polygon'
elif isinstance(segmentation, dict):
    mode = 'RLE'
elif isinstance(segmentation, str):
    mode = 'cRLE'
else:
    raise ValueError("Invalid argument type for argument `segmentation`. "
                     "Input `segmentation` should have a list, dictionary, or string type.")
```

2024-10-10 08:48 UTC, valvgab-bh commented on src/cocohelper/utils/segmentation.py
> +class MaskConverter(ABC):
nice improvement ;)

2024-10-10 08:48 UTC, valvgab-bh commented on src/cocohelper/splitters/proportional.py
> +        for i in range(len(n_samples)):
why this addition? the for loop

2024-10-10 08:48 UTC, valvgab-bh commented on src/cocohelper/merge.py
> +            mask = (old_cats['name'] == cat['name'])
what does this handle? can you comment on this else statement?

2024-10-17 07:35 UTC, paudaniele-bh commented on tests/unit/test_cocohelper/test_merger.py
I accidentally deleted in previous commits but I fixed it, now it is there and is updated.

2024-10-17 07:40 UTC, paudaniele-bh commented on tests/unit/test_cocohelper/test_dataset_adapter.py
> +def clean_saved_coco():
it is used in test_binary_reader for deleting a folder that is dynamically created during the test.

2024-10-17 07:56 UTC, paudaniele-bh commented on src/cocohelper/utils/segmentation.py
> +    return 'cRLE'
Done!

2024-10-17 07:57 UTC, paudaniele-bh commented on src/cocohelper/utils/segmentation.py
> +class MaskConverter(ABC):
<3

2024-10-17 08:13 UTC, paudaniele-bh commented on src/cocohelper/splitters/proportional.py
> +        for i in range(len(n_samples)):
there was a bug: i tested that for some pairs (n_images : proportions) the old code return n_sample where sum(n_samples) < n_images, but we want that sum(n_samples) == n_images. 
My function fixed the bug

2024-10-17 08:18 UTC, paudaniele-bh commented on src/cocohelper/merge.py
> +            mask = (old_cats['name'] == cat['name'])
because 'supercategory' is a recommended key and not mandatory, accordingly with coco format and with our validation (check in validator.py line 283) so without if else it raise an Exception whether 'supercategory' is not present but is wrong.

2024-10-17 09:32 UTC, paudaniele-bh commented on src/cocohelper/stats.py
>          return _df.to_dict()
I created __get_category_ratios because __get_annotations_ratios didnt do what is was supposed to do. It was used in cat_nms_ratios and cat_ids_ratios: the docstring of both says 'For each category, compute how many images in the dataset contains at least an annotation for that category'. But this is not what __get_annotations_ratios does, in fact __get_annotations_ratios counts the number of instances in our dataset, and it does it for only a category subset (those that appear in the dataset). The function __get_category_ratios instead calculates for each category (also those that never appear in the dataset) the number of images in which they appear at least once for that category.

2024-10-17 09:37 UTC, paudaniele-bh commented on src/cocohelper/stats.py
> +        # join the annotations with the images and the categories, removes duplicates and NaN values
Check the prev comment for more details:
With this function we keep track of categories that are not used, in fact the output is a dict where for each category we have a value in the range [0,1] where 0 means never used and 1 means used at least once in each image of the dataset.
If you mean we have to track other info then we have to define specific new functions.

2024-10-17 09:45 UTC, paudaniele-bh commented on tests/unit/test_cocohelper/test_dataset_adapter.py
> +    # remove images that are not present in masks
The test it was able sometimes to create the mask for each image, this creates a misalignment between images and masks and it raised an Exception. This is a check to ensure to re-align images and masks and only existing files are processed.

2024-10-17 10:15 UTC, paudaniele-bh commented on tests/unit/test_cocohelper/test_stats.py
> -        -1: 0.041666666666666664,  # -1 is for images having no annotation
If you check my comments in stats.py you understand that -1/'NA' do not have anymore sense and they can be removed. In fact the output of stats.cat_ids_ratios is a dict where for each category we have a value in range [0,1] expressing in percentage the number of images that category appears at least once: 0 mean it never appears, 1 means it appears at least once in all images.

2024-10-22 13:37 UTC, valvgab-bh commented on tests/unit/test_cocohelper/test_stats.py
> -        -1: 0.041666666666666664,  # -1 is for images having no annotation
but this is removing a feature, right? what if a user wants to know how many unlabelled images are in the dataset? is there any alternative way?

2024-10-22 13:38 UTC, valvgab-bh commented on tests/unit/test_cocohelper/test_stats.py
> -        '<NA>': 0.041666666666666664,  # <NA> is for images having no annotation
see my comment above

2024-10-22 13:39 UTC, valvgab-bh commented on src/cocohelper/stats.py
> +        # join the annotations with the images and the categories, removes duplicates and NaN values
again, see my comment above. Checking labels never used is different from checking how many images have no labels inside

2024-10-22 13:39 UTC, valvgab-bh commented on tests/unit/test_cocohelper/test_stats.py
> -        -1: 0.041666666666666664,  # -1 is for images having no annotation
notice that checking labels never used is different from checking how many images have no labels inside

2024-10-22 14:02 UTC, valvgab-bh commented on tests/unit/test_cocohelper/test_stats.py
> -        -1: 0.041666666666666664,  # -1 is for images having no annotation
ok, understood, it's for #14 
Agreed on the change. Please offer a simple property returning number of unlabelled images in the dataset

2024-10-22 14:02 UTC, valvgab-bh commented on tests/unit/test_cocohelper/test_stats.py
> -        '<NA>': 0.041666666666666664,  # <NA> is for images having no annotation
closed #14

2024-10-22 14:02 UTC, valvgab-bh commented on src/cocohelper/stats.py
> +        # join the annotations with the images and the categories, removes duplicates and NaN values
closes #14

2024-10-22 14:48 UTC, paudaniele-bh commented on tests/unit/test_cocohelper/test_stats.py
> -        -1: 0.041666666666666664,  # -1 is for images having no annotation
The property nb_imgs_wo_anns has been added to return the number of images without any annotations, the unit test has been added as well.

2024-10-23 08:08 UTC, merged