Docs
AILAB-bh/cocohelper pull request #4
Opened 2022-12-20 10:19 UTC by valvgab-bh

Improve documentation

2022-12-20 10:19 UTC, valvgab-bh commented
@delchiaro-bh please have a look at the file headers, modify if needed

2022-12-21 17:15 UTC, delchiaro-bh commented on src/cocohelper/adapters/dataset_adapter.py
> +"""A generic adapter for converting datasets an arbitrary format to COCO format.
The abstraction of an Adapter ...

2022-12-21 17:15 UTC, delchiaro-bh commented on src/cocohelper/__init__.py
> +"""A Python API to make working with COCO simpler.
I would change to: with the COCO dataset format

2022-12-21 17:16 UTC, delchiaro-bh commented on src/cocohelper/errors/__init__.py
> +"""Custom errors for the library.
I suggest to use *exception* word for documenting, it's easier to understand for everybody

2022-12-21 17:17 UTC, delchiaro-bh commented on src/cocohelper/errors/not_found_error.py
> +"""Errors for not found items in the COCO dataset.
Exceptions raised when items are not found in COCO dataset

2022-12-21 17:18 UTC, delchiaro-bh commented on src/cocohelper/errors/validation_error.py
> +"""Errors for non-valid COCO dataset.
Exception raised when assertion of dataset validity fails

2022-12-21 17:20 UTC, delchiaro-bh commented on src/cocohelper/filters/cocofilters/__init__.py
> +"""Filters for the COCO data.
Special and complex filters to obtain specific data from COCO tables using the COCOHelper interface.

2022-12-21 17:25 UTC, delchiaro-bh commented on src/cocohelper/filters/cocofilters/cocofilters.py
> +"""Filters for the COCO images, annotations, and categories.
Special and complex filters used to obtain specific data from COCO `images`, `annotations` and `categories` tables.

2022-12-21 17:26 UTC, delchiaro-bh commented on src/cocohelper/filters/strategies/__init__.py
> +"""Filtering strategies.
Filtering strategies for ValueFilter and RangeFilter.

2022-12-21 17:29 UTC, delchiaro-bh commented on src/cocohelper/utils/path.py
> +"""Utils paths.
Utilities* for path manipulation.

2022-12-21 17:29 UTC, delchiaro-bh commented on src/cocohelper/utils/segmentation.py
> +"""Utils for converting segmentation annotations between different formats.
Utilities*

2022-12-21 17:31 UTC, delchiaro-bh requested changes
Some of the docstrings are not so helpful to the library user, I made some comments.

If the docstring is a single line, please close the docstring in the same line:
```
"""Example of single-line docstring."""
```

Otherwise start from a new line and close in a new line:
```
"""
Example of multi-line docstring.
"""
```

2022-12-21 17:45 UTC, valvgab-bh commented
@delchiaro-bh everything should be fixed now

2022-12-22 08:23 UTC, merged